# Copyright (c) The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

self-hosted-runner:
  labels:
    # actionlint 1.7.12 does not recognize the Xcode-versioned images yet
    - xcode-27
    # PQCP runners
    - pqcp-arm64
    - pqcp-ppc64
    - pqcp-x64
    # RISE RISC-V runner
    - ubuntu-24.04-riscv
    - self-hosted-nucleo-n657x0
