# Copyright (c) The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

self-hosted-runner:
  labels:
    # actionlint 1.7.7 does not recognize macos-15-intel yet
    # TODO: Remove when upgrading to >= 1.7.8
    - macos-15-intel
    # PQCP runners
    - pqcp-arm64
    - pqcp-ppc64
    - pqcp-x64
