/*
 * Copyright (c) The mlkem-native project authors
 * SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT
 */

/* References
 * ==========
 *
 * - [REF_AVX2]
 *   CRYSTALS-Kyber optimized AVX2 implementation
 *   Bos, Ducas, Kiltz, Lepoint, Lyubashevsky, Schanck, Schwabe, Seiler, Stehlé
 *   https://github.com/pq-crystals/kyber/tree/main/avx2
 */

/*
 * This file is derived from the public domain
 * AVX2 Kyber implementation @[REF_AVX2].
 */

#include "../../../common.h"

#if defined(MLK_ARITH_BACKEND_X86_64_DEFAULT) && \
    !defined(MLK_CONFIG_MULTILEVEL_NO_SHARED)

#include "consts.h"

MLK_ALIGN const int16_t mlk_qdata[624] = {

#define MLK_AVX2_BACKEND_DATA_OFFSET_REVIDXB 0
    /* TODO: Explain these numbers */
    /* check-magic: off */
    3854, 3340, 2826, 2312, 1798, 1284, 770, 256,
    3854, 3340, 2826, 2312, 1798, 1284, 770, 256,
/* check-magic: on */

#define MLK_AVX2_BACKEND_DATA_OFFSET_REVIDXD 16
    7,    0,    6,    0,    5,    0,    4,   0,
    3,    0,    2,    0,    1,    0,    0,   0,

#define MLK_AVX2_BACKEND_DATA_OFFSET_ZETAS_EXP 32
#include "x86_64_zetas.i"

#define MLK_AVX2_BACKEND_DATA_OFFSET_MULCACHE_TWIDDLES 496
#include "x86_64_mulcache_twiddles.i"
};

#else /* MLK_ARITH_BACKEND_X86_64_DEFAULT && !MLK_CONFIG_MULTILEVEL_NO_SHARED \
       */

MLK_EMPTY_CU(avx2_consts)

#endif /* !(MLK_ARITH_BACKEND_X86_64_DEFAULT && \
          !MLK_CONFIG_MULTILEVEL_NO_SHARED) */

/* To facilitate single-compilation-unit (SCU) builds, undefine all macros.
 * Don't modify by hand -- this is auto-generated by scripts/autogen. */
/* Some macros are kept because they are also defined in a header. */
/* Keep: MLK_AVX2_BACKEND_DATA_OFFSET_REVIDXB (consts.h) */
/* Keep: MLK_AVX2_BACKEND_DATA_OFFSET_REVIDXD (consts.h) */
/* Keep: MLK_AVX2_BACKEND_DATA_OFFSET_ZETAS_EXP (consts.h) */
/* Keep: MLK_AVX2_BACKEND_DATA_OFFSET_MULCACHE_TWIDDLES (consts.h) */
