# SPDX-License-Identifier: Apache-2.0

name: CT Test
description: Builds the library with given flags and runs Valgrind-based constant-time tests

inputs:
  cflags:
    description: CFLAGS to pass to compilation
    default: ""
  valgrind_flags:
    description: Extra flags to pass to valgrind
    default: ""
  ctllvm:
    description: whether to run CT-LLVM or not (requires LLVM)
    default: "false"

runs:
  using: composite
  steps:
      - name: System info
        shell: ${{ env.SHELL }}
        run: |
          ARCH=$(uname -m)
          echo <<-EOF
            ## Setup
            Architecture: $ARCH
            - $(uname -a)
            - $(nix --version || echo 'nix not present')
            - $(bash --version | grep -m1 "")
            - $(python3 --version)
            - $(${{ inputs.cross_prefix }}${CC} --version | grep -m1 "")
          EOF
          cat >> $GITHUB_STEP_SUMMARY <<-EOF
            ## Setup
            Architecture: $ARCH
            - $(uname -a)
            - $(nix --version || echo 'nix not present')
            - $(bash --version | grep -m1 "")
            - $(python3 --version)
            - $(${{ inputs.cross_prefix }}${CC} --version | grep -m1 "")
          EOF
      - shell: ${{ env.SHELL }}
        run: |
          make clean
          tests func --exec-wrapper="valgrind --error-exitcode=1 --track-origins=yes ${{ inputs.valgrind_flags }}" --cflags="-DMLK_CT_TESTING_ENABLED -DNTESTS=50 ${{ inputs.cflags }}"
      - shell: ${{ env.SHELL }}
        if: ${{ inputs.ctllvm == 'true' }}
        run: |
          make -C test/ctllvm
      - shell: ${{ env.SHELL }}
        if: ${{ inputs.ctllvm == 'true' }}
        run: | 
          make clean
          tests func --cflags="-fpass-plugin=test/ctllvm/ctllvm.so"-g ${{ inputs.cflags }}"
