# Copyright (c) The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

# WARNING: This file is auto-generated by scripts/autogen.
# Do not edit it directly. Instead, edit the YAML 'ABI.Features:'
# list in dev/<arch>/src/<kernel>.S and run scripts/autogen.
#
# For each capability declared by some kernel's ABI.Features list,
# this file appends the capability's CFLAGS to that kernel's
# (shipped, in-tree) .S object under mlkem/src/.

# Default each cap's file list to empty so unconditional appends
# below are safe even when a cap has no kernels on this arch.
ABICHECK_REQ_VSX_FILES :=

# VSX: PPC64 VSX/Altivec (POWER8)
ABICHECK_REQ_VSX_FILES := \
  mlkem/src/native/ppc64le/src/intt_ppc_asm.S \
  mlkem/src/native/ppc64le/src/ntt_ppc_asm.S \
  mlkem/src/native/ppc64le/src/poly_tomont_ppc_asm.S \
  mlkem/src/native/ppc64le/src/reduce_ppc_asm.S \
  test/abicheck/ppc64le/callstub_ppc64le.S \
  test/abicheck/ppc64le/selftest_ppc64le.S
ABICHECK_REQ_VSX_OBJS := $(call MAKE_OBJS,$(ABICHECK_DIR),$(ABICHECK_REQ_VSX_FILES))
$(ABICHECK_REQ_VSX_OBJS): CFLAGS += -mcpu=power8 -maltivec -mvsx
