theory MLKEM_Verify_Definitions
  imports "Micro_C_Examples.Simple_C_Functions"
begin

text \<open>
  Auto-generated by @{file "pipeline/generate.py"} from preprocessed C.
  Source unit: @{file "mlkem/src/verify.c"}
  Preprocessed unit: @{file "generated/c/verify.pre.c"}
\<close>

micro_c_file "generated/c/verify.pre.c"

end
