theory MLKEM_Poly_Definitions
  imports
    MLKEM_Machine_Model
begin

text \<open>
  Auto-generated by @{file "pipeline/generate.py"} from preprocessed C.
  Source unit: @{file "../../mlkem/src/poly.c"}
  Preprocessed unit: @{file "generated/c/poly.pre.c"}
\<close>

context c_mlk_machine_model
begin

micro_c_file addr: 'addr gv: 'gv manifest: "generated/manifests/poly.functions.manifest" "generated/c/poly.pre.c"

end


end
