/*
 * Copyright (c) The mlkem-native project authors
 * SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT
 */

#include "../../../../common.h"
#include "../../../../verify.h"

#if defined(MLK_FIPS202_ARMV81M_NEED_X1) && \
    !defined(MLK_CONFIG_MULTILEVEL_NO_SHARED)

#include <stdint.h>
#include "fips202_native_armv81m.h"

void mlk_keccak_f1600_x1_state_extract_bytes_impl(uint64_t *state,
                                                  uint8_t *data,
                                                  unsigned offset,
                                                  unsigned length)
{
  mlk_keccak_f1600_x1_state_extract_bytes_asm(state, data, offset, length);
}

void mlk_keccak_f1600_x1_state_xor_bytes_impl(uint64_t *state,
                                              const uint8_t *data,
                                              unsigned offset, unsigned length)
{
  mlk_keccak_f1600_x1_state_xor_bytes_asm(state, data, offset, length);
}


#define mlk_keccak_f1600_x1_native_impl \
  MLK_NAMESPACE(keccak_f1600_x1_native_impl)
int mlk_keccak_f1600_x1_native_impl(uint64_t *state)
{
  /* Run the permutation */
  mlk_keccak_f1600_x1_armv7m_asm((void *)state,
                                 mlk_keccakf1600_round_constants);
  return MLK_NATIVE_FUNC_SUCCESS;
}

#else /* MLK_FIPS202_ARMV81M_NEED_X1 && !MLK_CONFIG_MULTILEVEL_NO_SHARED */

MLK_EMPTY_CU(keccak_f1600_x1_armv7m)

#endif /* !(MLK_FIPS202_ARMV81M_NEED_X1 && !MLK_CONFIG_MULTILEVEL_NO_SHARED) \
        */

/* To facilitate single-compilation-unit (SCU) builds, undefine all macros.
 * Don't modify by hand -- this is auto-generated by scripts/autogen. */
/* Some macros are kept because they are also defined in a header. */
/* Keep: mlk_keccak_f1600_x1_native_impl (mve.h) */
