# Copyright (c) The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

# WARNING: This file is auto-generated by scripts/autogen.
# Do not edit it directly. Instead, edit the YAML 'ABI.Features:'
# list in dev/<arch>/src/<kernel>.S and run scripts/autogen.
#
# For each capability declared by some kernel's ABI.Features list,
# this file appends the capability's CFLAGS to that kernel's
# (shipped, in-tree) .S object under mlkem/src/.

# Default each cap's file list to empty so unconditional appends
# below are safe even when a cap has no kernels on this arch.
ABICHECK_REQ_SHA3_FILES :=

# SHA3: Armv8.4-A SHA3 (eor3, rax1, xar, bcax)
ABICHECK_REQ_SHA3_FILES := \
  mlkem/src/fips202/native/aarch64/src/keccak_f1600_x1_v84a_aarch64_asm.S \
  mlkem/src/fips202/native/aarch64/src/keccak_f1600_x2_v84a_aarch64_asm.S \
  mlkem/src/fips202/native/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_aarch64_asm.S
ABICHECK_REQ_SHA3_OBJS := $(call MAKE_OBJS,$(ABICHECK_DIR),$(ABICHECK_REQ_SHA3_FILES))
$(ABICHECK_REQ_SHA3_OBJS): CFLAGS += -march=armv8.4-a+sha3
