theory {THEORY_NAME}
  imports
    MLKEM_Machine_Model
begin

text \<open>
  Auto-generated by @{file "pipeline/generate.py"} from preprocessed C.
  Source unit: @{file "../../{SOURCE_FILE}"}
  Preprocessed unit: @{file "{PREPROCESSED_FILE}"}
\<close>

{ISABELLE_PRELUDE}{MICRO_C_FILE_COMMANDS}
{ISABELLE_POSTLUDE}

end
