theory {THEORY_NAME}
  imports
    MLKEM_Machine_Model
begin

text \<open>
  Auto-generated by @{file "pipeline/generate.py"} from preprocessed C.
  Source unit: @{file "../../{SOURCE_FILE}"}
  Preprocessed unit: @{file "{PREPROCESSED_FILE}"}
\<close>

{ISABELLE_PRELUDE}micro_c_file {MICRO_C_FILE_OPTIONS}"{PREPROCESSED_FILE}"

{ISABELLE_POSTLUDE}

end
