# Copyright (c) The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: CBMC
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:

jobs:
  cbmc:
    name: CBMC (ML-KEM-${{ matrix.level }})
    if: ${{ github.repository_owner == 'pq-code-package' && !github.event.pull_request.head.repo.fork }}
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    strategy:
      fail-fast: false
      matrix:
        include:
          - k: 2
            level: 512
          - k: 3
            level: 768
          - k: 4
            level: 1024
    uses: ./.github/workflows/ci_ec2_reusable.yml
    with:
      name: CBMC (MLKEM-${{ matrix.level }})
      ec2_instance_type: r8g.xlarge
      ec2_ami: ubuntu (aarch64)
      ec2_volume_size: 20
      compile_mode: native
      opt: no_opt
      lint: false
      verbose: true
      test: false
      cbmc: true
      cbmc_mlkem_k: ${{ matrix.k }}
    secrets: inherit
