# Copyright (c) The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: Lint-Markdown
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint-markdown-link:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Check markdown links
      run: |
        npm install -g markdown-link-check@3.14.2
        find . -name '*.md' -print0 | xargs -0 -P16 -n1 markdown-link-check -q -c .github/mlc_config.json
