# Copyright (c) The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: RISC-V
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:
jobs:
  quickcheck:
    name: Quickcheck (riscv)
    if: ${{ github.repository_owner == 'pq-code-package' && !github.event.pull_request.head.repo.fork }}
    # via https://riseproject-dev.github.io/riscv-runner/
    runs-on: ubuntu-24.04-riscv
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: make quickcheck
        run: |
          OPT=0 make quickcheck
          make clean >/dev/null
          OPT=1 make quickcheck
      - uses: ./.github/actions/setup-os
      - name: tests func
        run: |
          ./scripts/tests func --check-namespace
